import "../styles/globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { AppSidebar } from "@/components/app-sidebar";
import { ReactQueryProvider } from "@/provider/react-query-client";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <ReactQueryProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>{children}</SidebarInset>
          </SidebarProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
